### ISSUE TITLE
Compilation failed when trying to find prime access pattern for non-inclusive cache

### ISSUE THREAD

**Issue by FxPiGaAo** [KULeuven-COSIC/PRIME-SCOPE#2]
In order to run execute_PS.sh for my non-inclusive LLC, I changed line 10 in primeapp/configuration.h into #define LLC_NONINCLUSIVE. But after that, the compilation failed. Here is the output:

> Increasing stack size...
> ~/my_spectre_attack/experiment/primeprobe/primetime/primebot ~/my_spectre_attack/experiment/primeprobe/primetime
> Writing Patterns [to ../log/patterns0.txt]
> Number of primes: 14110
> ~/my_spectre_attack/experiment/primeprobe/primetime
> ~/my_spectre_attack/experiment/primeprobe/primetime/primebot ~/my_spectre_attack/experiment/primeprobe/primetime
> Reading Primes [from ../log/patterns0.txt]
> Writing Patterns [to ../log/input.txt]
> Creating Code Files
> Number of primes: 14110
> ~/my_spectre_attack/experiment/primeprobe/primetime
> ~/my_spectre_attack/experiment/primeprobe/primetime/primeapp ~/my_spectre_attack/experiment/primeprobe/primetime
> rm -rf app 
> rm -rf obj
> rm -rf log/output.txt
> make clean -C ../../evsets//
> make[1]: Entering directory '/home/xhc/my_spectre_attack/experiment/primeprobe/evsets'
> rm -rf obj
> make[1]: Leaving directory '/home/xhc/my_spectre_attack/experiment/primeprobe/evsets'
> make clean -C ../../utils//
> make[1]: Entering directory '/home/xhc/my_spectre_attack/experiment/primeprobe/utils'
> rm -rf obj
> make[1]: Leaving directory '/home/xhc/my_spectre_attack/experiment/primeprobe/utils'
> make -C ../../utils/ 
> make[1]: Entering directory '/home/xhc/my_spectre_attack/experiment/primeprobe/utils'
> cc -I./obj -fPIC -c cache_utils.c -o obj/./cache_utils.o
> cc -I./obj -fPIC -c memory_utils.c -o obj/./memory_utils.o
> cc -I./obj -fPIC -c misc_utils.c -o obj/./misc_utils.o
> make[1]: Leaving directory '/home/xhc/my_spectre_attack/experiment/primeprobe/utils'
> make -C ../../evsets/ CONFIG_FILE=/home/xhc/my_spectre_attack/experiment/primeprobe/primetime/primeapp//configuration.h
> make[1]: Entering directory '/home/xhc/my_spectre_attack/experiment/primeprobe/evsets'
> cc -I./obj -fPIC -std=gnu99 -c ps_evset_noninc.c -include /home/xhc/my_spectre_attack/experiment/primeprobe/primetime/primeapp//configuration.h -o obj/ps_evset_noninc.o
> cc -I./obj -fPIC -std=gnu99 -c ps_evset_inc.c -include /home/xhc/my_spectre_attack/experiment/primeprobe/primetime/primeapp//configuration.h -o obj/ps_evset_inc.o
> cc -I./obj -fPIC -std=gnu99 -c list/list_utils.c -include /home/xhc/my_spectre_attack/experiment/primeprobe/primetime/primeapp//configuration.h -o obj/list_utils.o
> cc -I./obj -fPIC -std=gnu99 -c list/list_traverse.c -include /home/xhc/my_spectre_attack/experiment/primeprobe/primetime/primeapp//configuration.h -o obj/list_traverse.o
> make[1]: Leaving directory '/home/xhc/my_spectre_attack/experiment/primeprobe/evsets'
> cc -I./obj  -I../../evsets//obj -I../../utils//obj -c main.c -o obj/main.o
> cc -I./obj  -I../../evsets//obj -I../../utils//obj -c attacker_arr.c -o obj/attacker_arr.o
> attacker_arr.c: In function ‘attacker’:
> attacker_arr.c:192:7: warning: implicit declaration of function ‘ps_evset’; did you mean ‘ps_evset_l2’? [-Wimplicit-function-declaration]
>   192 |   i = ps_evset(evset_ptr, (char*)TARGET, LLC_WAYS, evict_mem, HUGE_PAGES_AVAILABLE, SW_THR);
>       |       ^~~~~~~~
>       |       ps_evset_l2
> attacker_arr.c:202:7: error: too few arguments to function ‘ps_evset_test’
>   202 |   if (ps_evset_test(evset_ptr, (char*)TARGET, SW_THR, 100, EVTEST_MEDIAN))
>       |       ^~~~~~~~~~~~~
> In file included from configuration.h:87,
>                  from attacker_arr.c:10:
> ../../evsets/ps_evset.h:47:6: note: declared here
>    47 | int  ps_evset_test  (Elem **evset, char *victim, int threshold, int test_len, int test_method, int is_cd);
>       |      ^~~~~~~~~~~~~
> make: *** [Makefile:40: obj/attacker_arr.o] Error 1

Did I miss any step? I only modified that specific line.

**Comment by furkanturan** [comment]
Hello,

The problem is that primetime is only for **inclusive Intel LLCs**. 
That is indicated on its [readme](https://github.com/KULeuven-COSIC/PRIME-SCOPE/blob/main/primetime/README.md).

As provided on Table 1 of [Prime+Scope paper](https://www.esat.kuleuven.be/cosic/publications/article-3405.pdf), we used alternating pointer chasing based access patterns on non-inclusive caches.

Kind Regards,
Furkan
